@ECHO OFF

IF "VMKC-TEST"=="%COMPUTERNAME%" (
  GOTO COMPUTERNAME_MACHINENAME_EQUAL
) ELSE (
  GOTO COMPUTERNAME_MACHINENAME_NOT_EQUAL
) 
GOTO COMPUTERNAME_MACHINENAME_CHECK_DONE


:COMPUTERNAME_MACHINENAME_EQUAL
  @ECHO Config.cmd::Initialising InstallTool values
  SET PS_BASEPATH=D:\InfoShare\Data\PublishingService
  SET PS_TOOLPATH=D:\InfoShare\App\Utilities\PublishingService\Tools
  SET PS_ERROROBJECTLOCATION=D:\InfoShare\App\Utilities\PublishingService\Resources
  SET PS_DITAOT=%CD%
  SET PS_UTILITIES=D:\InfoShare\App\Utilities
  SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0_162
  SET JHHOME=C:\javahelp\jh2.0
  SET AXF_DIR=C:\Program Files\Antenna House\AHFormatterV65
  SET AXF_OPT=D:\InfoShare\App\Utilities\AntennaHouse\XSLFormatter\XfoSettings.xml
  REM SET XEP_DIR=C:\Program Files\Antenna House\AHFormatterV65
  REM SET PE_DIR=C:\Program Files\Antenna House\AHFormatterV65
  SET HHCDIR=C:\Program Files (x86)\HTML Help Workshop
  SET PDF_FORMATTER=ah
  GOTO COMPUTERNAME_MACHINENAME_CHECK_DONE
  
:COMPUTERNAME_MACHINENAME_NOT_EQUAL
  @ECHO Config.cmd::Initialising default values
  @ECHO.  *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
  @ECHO.  *-* Config.cmd::ATTENTION THE INSTALLTOOL VARIABLES ARE INCORRECT *-*
  @ECHO.  *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
  SET PS_BASEPATH=C:\InfoShare\Data\PublishingService
  SET PS_TOOLPATH=%PS_BASEPATH%\Tools
  SET PS_ERROROBJECTLOCATION=%PS_BASEPATH%\Resources
  SET PS_DITAOT=%CD%
  SET PS_UTILITIES=C:\InfoShare\App\Utilities
  SET JAVA_HOME=C:\Program Files\Java\jre8
  SET JHHOME=C:\javahelp\jh2.0
  SET AXF_OPT=%PS_UTILITIES%\AntennaHouse\XSLFormatter\XfoSettings.xml
  SET HHCDIR=C:\Program Files\HTML Help Workshop
  SET PDF_FORMATTER=ah  
  GOTO COMPUTERNAME_MACHINENAME_CHECK_DONE


:COMPUTERNAME_MACHINENAME_CHECK_DONE



SET ANT_HOME=%PS_DITAOT%
SET PATH=%JAVA_HOME%\bin;%ANT_HOME%\bin;%PATH%

SET CLASSPATH=%PS_DITAOT%\lib;%PS_DITAOT%\lib\dost.jar;%PS_DITAOT%\lib\resolver.jar;%PS_DITAOT%\lib\icu4j.jar;%CLASSPATH%
SET CLASSPATH=%PS_DITAOT%\lib\commons-codec-1.4.jar;%PS_DITAOT%\lib\xercesImpl.jar;%PS_DITAOT%\lib\xml-apis.jar;%CLASSPATH%
SET CLASSPATH=%PS_DITAOT%\lib\saxon\saxon9.jar;%PS_DITAOT%\lib\saxon\saxon9-dom.jar;%CLASSPATH%

IF %PROCESSOR_ARCHITECTURE%==AMD64 (
  SET ANT_OPTS=-Xmx4096m -Xss20m %ANT_OPTS%
) ELSE (
  SET ANT_OPTS=-Xmx1500m -Xss20m %ANT_OPTS%  
)
SET ANT_OPTS=%ANT_OPTS% -Djavax.xml.transform.TransformerFactory=net.sf.saxon.TransformerFactoryImpl

CALL :PRINT_AND_VALIDATE_PATH PS_BASEPATH "%PS_BASEPATH%"
CALL :PRINT_AND_VALIDATE_PATH PS_UTILITIES "%PS_UTILITIES%"
CALL :PRINT_AND_VALIDATE_PATH PS_TOOLPATH "%PS_TOOLPATH%"
CALL :PRINT_AND_VALIDATE_PATH PS_ERROROBJECTLOCATION "%PS_ERROROBJECTLOCATION%"
CALL :PRINT_AND_VALIDATE_PATH PS_DITAOT "%PS_DITAOT%"
CALL :PRINT_AND_VALIDATE_PATH JAVA_HOME "%JAVA_HOME%"
CALL :PRINT_AND_VALIDATE_PATH JHHOME "%JHHOME%"
CALL :PRINT_AND_VALIDATE_PATH AXF_DIR "%AXF_DIR%"
CALL :PRINT_AND_VALIDATE_FILEPATH AXF_OPT "%AXF_OPT%"
CALL :PRINT_AND_VALIDATE_PATH XEP_DIR "%XEP_DIR%"
CALL :PRINT_AND_VALIDATE_PATH PE_DIR "%PE_DIR%"
CALL :PRINT_AND_VALIDATE_PATH HHCDIR "%HHCDIR%"
CALL :PRINT_PARAMETER PDF_FORMATTER "%PDF_FORMATTER%"
CALL :PRINT_PARAMETER PATH "%PATH%"
CALL :PRINT_PARAMETER CLASSPATH "%CLASSPATH%"
CALL :PRINT_PARAMETER ANT_OPTS "%ANT_OPTS%"
CALL :PRINT_PARAMETER TEMP "%TEMP%"
CALL :PRINT_PARAMETER TMP "%TMP%"
CALL :PRINT_PARAMETER PROCESSOR_ARCHITECTURE "%PROCESSOR_ARCHITECTURE%"
CALL :PRINT_PARAMETER DOMAIN\USERNAME "%USERDOMAIN%\%USERNAME%"
GOTO THE_END


:PRINT_AND_VALIDATE_PATH
IF %2=="" (
  GOTO PRINT_AND_VALIDATE_PATH_EMPTY  
) ELSE (
  IF NOT EXIST %2 (
    GOTO PRINT_AND_VALIDATE_PATH_NOT_EXISTS  
  ) ELSE (
    GOTO PRINT_AND_VALIDATE_PATH_EXISTS  
  )
)
GOTO :EOF


:PRINT_AND_VALIDATE_PATH_EMPTY
  @ECHO %1 is empty
  GOTO :EOF

:PRINT_AND_VALIDATE_PATH_NOT_EXISTS
  @ECHO.  *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
  @ECHO.  *-* Config.cmd::VALUE OF PARAMETER %1 IS NOT A FOLDER
  @ECHO.  *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
  @ECHO. %1=%2
  GOTO :EOF

:PRINT_AND_VALIDATE_PATH_EXISTS
  @ECHO. %1=%2
  GOTO :EOF



:PRINT_AND_VALIDATE_FILEPATH
IF %2=="" (
  GOTO PRINT_AND_VALIDATE_FILEPATH_EMPTY  
) ELSE (
  IF NOT EXIST %2 (
    GOTO PRINT_AND_VALIDATE_FILEPATH_NOT_EXISTS  
  ) ELSE (
    GOTO PRINT_AND_VALIDATE_FILEPATH_EXISTS 
  )
)
GOTO :EOF


:PRINT_AND_VALIDATE_FILEPATH_EMPTY
  @ECHO %1 is empty
  GOTO :EOF

:PRINT_AND_VALIDATE_FILEPATH_NOT_EXISTS
  @ECHO.  *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
  @ECHO.  *-* Config.cmd::VALUE OF PARAMETER %1 IS NOT A FILE
  @ECHO.  *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
  @ECHO. %1=%2
  GOTO :EOF

:PRINT_AND_VALIDATE_FILEPATH_EXISTS
  @ECHO. %1=%2
  GOTO :EOF



:PRINT_PARAMETER
IF %2=="" (
  GOTO PRINT_PARAMETER_EMPTY  
) ELSE (
  GOTO PRINT_PARAMETER_NOT_EMPTY
)
GOTO :EOF

:PRINT_PARAMETER_EMPTY
  @ECHO. %1 is empty!
  GOTO :EOF

:PRINT_PARAMETER_NOT_EMPTY
  @ECHO. %1=%2
  GOTO :EOF



:THE_END
@ECHO ON
